### PR TITLE
Pedantic changes to texts of touchpad tap settings

### PR DESCRIPTION
**Pull request by tsujan**
They were a little confusing before.

### CODE REVIEW

**Comment by yan12125** [comment]
Thanks! Maybe "Tap twice and drag" is even clearer?

**Comment by tsujan** [comment]
> Maybe "Tap twice and drag" is even clearer?

The second movement isn't a tap; only the fist one is.

**Comment by tsujan** [comment]
> as tap twice and drag (3 actions in total) also works

Strange! Not here. If I tap twice on a GitHub image link, it'll be opened before I can drag it. I guess touchpads are different. Tapping and then dragging doesn't open the link but drags the image, as expected.

**Comment by yan12125** [comment]
> I guess touchpads are different.

Maybe. I use bcm5974 on MacBookAir7,2. Tap twice and drag works for folders and files in pcmanfm-qt :)

**Comment by tsujan** [comment]
Maybe we don't mean the same thing.

One tapping = Hitting + moving the finger away from touchpad. The second time, the finger hits the pad and slides on it (no tapping). Hence, it's one tapping and one dragging (= hit+slide).

If not, our touchpads are really different.

**Comment by yan12125** [comment]
We do have different touchpads :)

**Comment by yan12125** [comment]
Oops, I almost forgot this PR. Merged as it's simple and just correct.

**Pull request merged**
