### PR TITLE
Added a separate page for GTK style settings

### PR DESCRIPTION
**Pull request by tsujan**
Closes https://github.com/lxqt/lxqt-config/issues/817

### CODE REVIEW

**Review by palinek — COMMENTED** [review]
Just compiled and clicked through the GUI... seems good to me.

**Comment by stefonarch** [comment]
The information about the backups of existing gtk .ini files got lost?

**Comment by tsujan** [comment]
> The information about the backups of existing gtk .ini files got lost?

I didn't remove anything, at least, not intentionally. Please be more specific: what's missing?

**Comment by tsujan** [comment]
Wow, yes, something is missing! My bad. Will add it soon.

**Review by stefonarch — APPROVED** [review]
GTM

**Comment by tsujan** [comment]
It was only a cut-and-paste job. Let's see if git users find a problem in it.

**Pull request merged**
