### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-config/) for LXQt Configuration/lxqt-config.

### CODE REVIEW

**Comment by stefonarch** [comment]
@yan12125  @tsujan Any idea what happened here in lv and zh_CN ? Weblate got mad? Some weird hacking attempt? 
https://translate.lxqt-project.org/translate/lxqt-configuration/lxqt-config-locale/zh_CN/?checksum=2e0393827df96822&q=settings&sort_by=-priority%2Cposition

**Comment by stefonarch** [comment]
Atm blocking this user  https://translate.lxqt-project.org/projects/andrew-bibb/#history

**Comment by tsujan** [comment]
> Any idea what happened here in

I know nothing of the language... but isn't it like a locale issue?

**Comment by tsujan** [comment]
> No, it looks like a crypto currency hash

Yes! Now I see why you blocked that user.

**Comment by yan12125** [comment]
Thanks a lot, blocking the user is good. We also need to revert these changes: https://translate.lxqt-project.org/changes/?user=Todd

**Comment by stefonarch** [comment]
Saving the good changes somewhere and reset the repo will do for us, for  CMST I think I've to reinsert the correct translations.

**Comment by stefonarch** [comment]
Cleaned up.

**Pull request merged**
