### PR TITLE
Improve

### PR DESCRIPTION
**Pull request by luis-pereira**

### CODE REVIEW

**Comment by tsujan** [comment]
GTM

@luis-pereira 
I'm also worried about warnings like the following :
```
lxqt-config-monitor/monitor.h:27:8: warning: ‘monitor.MonitorSettings::rotation’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   27 | struct MonitorSettings {
      |        ^~~~~~~~~~~~~~~
/tmp/compilation/lxqt-config-improve/lxqt-config-monitor/monitorsettingsdialog.cpp:169:25: note: ‘monitor.MonitorSettings::rotation’ was declared here
  169 |         MonitorSettings monitor;
      |                         ^~~~~~~
```
It seems to me that they may be serious mistakes in the code.

**Comment by luis-pereira** [comment]
Will take a look into it. There are too many warnings in some places.
--
Cumprimentos
Regards

A sexta, 29/05/2020, 20:53, tsujan <notifications@github.com> escreveu:

**Comment by tsujan** [comment]
> There are too many warnings in some places.

Yes. But this PR is good for merging as it is, IMHO.

**Comment by luis-pereira** [comment]
@tsujan I usually use clang. Just checked and clang doesn't complaints about maybe-uninitialized there.
https://github.com/lxqt/lxqt-config/pull/630 Solves the issue. It's not that bad.

**Pull request merged**
