### PR TITLE
Do not force openbox configs under LXQt

### PR DESCRIPTION
**Pull request by stefonarch**
Twin of https://github.com/lxqt/lxqt-panel/pull/1656

### CODE REVIEW

**Review by tsujan — APPROVED** [review]
GTM

**Comment by tsujan** [comment]
Some users might complain but I think it's the correct thing to do.

**Comment by stefonarch** [comment]
I was thinking about an WM menu in the settings, but as the default names of the config tools are not clear that's even worse,

**Comment by tsujan** [comment]
Being WM-agnostic is a smart thing in LXQt. Users can easily find the settings of their chosen WM.

**Pull request merged**
