### PR TITLE
fix: improve message about default monitor settings

### PR DESCRIPTION
**Pull request by schlumpf-malaga**
This message pops up quite frequently and had some grammatical errors. Please consider merging this improvement.

### CODE REVIEW

**Comment by stefonarch** [comment]
Thanks, GTM

**Comment by tsujan** [comment]
@stefonarch 
I wanted to give it a "GTM" too but hesitated due to changes in translation files..

Ship it if everything is OK.

**Comment by stefonarch** [comment]
Usually we did this in only in a second step - running `lxqt-transupdate` and then remove the "unfinished" with a script were translations were present.

**Comment by schlumpf-malaga** [comment]
Thanks!

**Pull request merged**
