### PR TITLE
Remember size of lxqt-config-input dialog

### PR DESCRIPTION
**Pull request by tsujan**
Closes https://github.com/lxqt/lxqt-config/issues/820

### CODE REVIEW

**Comment by stefonarch** [comment]
GTM, and looks as it solved also a stupid behaviour from kwin: it open always in the upper left corner.

**Comment by tsujan** [comment]
> looks as it solved also a stupid behaviour from kwin: it opened always in the upper left corner.

That has never happened here. But, recently, KWin's default behavior changed, especially its window positioning. I reversed it to the previous behavior as soon as I saw the change.

That being said, Qt always centers a dialog when it has no parent. If you saw that KWin put the dialog at another position under X11, you've encountered a regression in KWin.

**Comment by tsujan** [comment]
BTW, I have a feeling that you may have forgotten https://github.com/lxqt/lxqt-panel/pull/1731 and https://github.com/lxqt/qterminal/pull/919 ;)

**Comment by stefonarch** [comment]
The first I've forgotten, in qterminal I0m waiting for you :)
Will do this evening.

**Comment by tsujan** [comment]
> in qterminal I'm waiting for you :)

Why? Have I forgotten something?

> Will do this evening.

There's no rush at all; just don't forget them.

**Pull request merged**
