### PR TITLE
One "monitor" less

### PR DESCRIPTION
**Pull request by stefonarch**
Follow up from https://github.com/lxqt/lxqt-config/pull/1043#issuecomment-2340954282

### CODE REVIEW

**Comment by tsujan** [comment]
I think settings are *changed*, while devices are *adjusted*.

**Comment by stefonarch** [comment]
True. "Use LXQt Monitor Settings to change settings" ?

**Comment by tsujan** [comment]
"Set your preferences with LXQt Monitor Settings" is much better. Or "Adjust your screens with LXQt Monitor Settings".

**Comment by stefonarch** [comment]
I would vote for "Adjust your screens with LXQt Monitor Settings" but it's not a democracy  ;)

**Review by tsujan — APPROVED** [review]

**Pull request merged**
