### PR TITLE
Start `xsettingsd` on X11 only when GTK themes should be set

### PR DESCRIPTION
**Pull request by tsujan**
Closes https://github.com/lxqt/lxqt-config/issues/1049

### CODE REVIEW

**Comment by M4he** [comment]
I have not tested this code (currently have no means to) and just looked at the changed code but I wondered:

If the dialog is opened while the ControlGTKThemeEnabled option is disabled, then xsettingsd is not started (check does not trigger in `showAdvancedOptions`). This is desired.

But if the user now clicks the checkbox for "Set GTK themes" for the first time and then "Apply", the GTK files will be written but is xsettingsd started as a result? To me it seems it is not (only when ControlGTKThemeEnabled was true before the dialog opened).

I'd expect that if the checkbox is enabled and "Apply" is clicked in the same dialog instance, xsettingsd gets started (if not already running) to apply the changes to running applications immediately.

**Comment by tsujan** [comment]
> But if the user now clicks the checkbox for "Set GTK themes" for the first time

`xsettingsd` is started as soon as the box is checked. That can happen when the user checks it or when the dialog is shown with `ControlGTKThemeEnabled=true` in `~/.config/lxqt/lxqt-config-appearance.conf` (the code checks it).

**Comment by M4he** [comment]
> > But if the user now clicks the checkbox for "Set GTK themes" for the first time
> 
> `xsettingsd` is started as soon as the box is checked. That can happen when the user checks it or when the dialog is shown with `ControlGTKThemeEnabled=true` in `~/.config/lxqt/lxqt-config-appearance.conf` (the code checks it).

Okay sorry then I might have misinterpreted the code. I only saw the starting happen in `showAdvancedOptions` via `initControls` which I thought would only be called once when the dialog is initially opened.

**Comment by tsujan** [comment]
→ `GTKConfig::showAdvancedOptions` in the patch.

**Review by stefonarch — APPROVED** [review]
Works as expected.

**Comment by tsujan** [comment]
@stefonarch, thanks for the test! I think the code is simple enough to be merged.

**Pull request merged**
