### PR TITLE
Reorder XML .ui files to correct tab orders

### PR DESCRIPTION
**Pull request by isf63**
Reordered XML .ui files to correct tab orders throughout lxqt-config. Some files were stubborn and may require \<tabstops\>.

Affected files:
- lxqt-config-appearance/{gtkconfig.ui, fontsconfig.ui}
- liblxqt-config-cursor/selectwnd.ui
- lxqt-config-input/{keyboardconfig.ui, touchpadconfig.ui}
- lxqt-config-monitor/{managesavedsettings.ui, monitorwidget.ui}

The following may need a further `<tabstops>` section:
- lxqt-config-input/keyboardconfig.ui
- lxqt-config-input/keyboardlayoutconfig.ui
- lxqt-config-brightness/brightnesssettings.ui
- lxqt-config-monitor/monitorpicture.ui

### CODE REVIEW

**Review by tsujan — CHANGES_REQUESTED** [review]
Thanks for the hard job! Its review wasn't easy either, although it mostly consisted of searching the string `<item row="` with a text editor that highlighted the matches (like FeatherPad):

In `selectwnd.ui`, `<item row="0" column="0" colspan="6">` and `<item row="1" column="0" colspan="6">` don't seem to be in right places and the `<tabstops>` block hasn't been removed.

In `touchpadconfig.ui`, `<item row="1" column="1">` is misplaced and there's an empty line before `<item row="9" column="0" colspan="2">`.

Also, in `monitorwidget.ui`, a few blocks are misplaced.

**Comment by tsujan** [comment]
> Should be all good now!

Yes, it is :) Please squash the commits before I merge it.

**Comment by isf63** [comment]
Sorry, but I don't know how to squash commits and then push them apparently. I used `git rebase -i HEAD~5` to put the non-consecutive commits together and squash the last one into the first, but pushing fails. I'm not very familiar with Git.

**Review by tsujan — APPROVED** [review]

**Comment by tsujan** [comment]
No worries.

There are different ways and different opinions on the best way to squash commits. What follows is what I prefer.

Suppose that you want to squash your last 3 pushed commits (like with this PR). You could do it by switching to your branch and doing

```
git reset --soft HEAD~3
git commit
git push --force origin name_of_your_branch
```

The second command lets you have your comment on the squashed commit.

Please try it (or any other method you prefer) with you future contributions.

**Pull request merged**
