### PR TITLE
Standardized desktop files for settings

### PR DESCRIPTION
**Pull request by stefonarch**
Draft for standardize configuration desktop files. At a first glance only globalkeys needs updating.  Related to https://github.com/lxqt/lxqt-config/pull/1014

### CODE REVIEW

**Comment by tsujan** [comment]
The current changes are good. However,

 * Identical names and generic names (like in `lxqt-config-monitor`.desktop) don't cause a problem. KDE also has them in `systemsettings.desktop`.
 * Also, as far as I know, `GenericName` isn't a must when `Name` is generic — or even otherwise. Several desktop files (outside LXQt) lack it.

**Comment by stefonarch** [comment]
>GenericName isn't a must when Name is generic 

We show `GenericName` in the panel menus, not sure what happens without them.

**Comment by tsujan** [comment]
Where? I don't remember it. But if panel had a problem without it, it would be show up, because there are several desktop entries without `GenericName`.

**Comment by stefonarch** [comment]
> Where? I don't remember it. But if panel had a problem without it, we should have seen it, because there are several desktop entries without `GenericName`.

In the tooltip. Made a test, if `GenericName` is empty `Comment` is shown.

**Comment by tsujan** [comment]
Yes. So, there's no problem; its absence is taken into account.

**Comment by isf63** [comment]
Also for Appearance/Locale/Input -- "settings" in GenericName should be capitalized.

**Review by tsujan — APPROVED** [review]
GTM

**Pull request merged**
