### PR TITLE
Consider LXQt theme names case-insensitively

### PR DESCRIPTION
**Pull request by tsujan**
This is needed after https://github.com/lxqt/liblxqt/pull/308

### CODE REVIEW

**Comment by tsujan** [comment]
This need changes, for two reasons: (1) `lxqt-config` shouldn't need to know about case-insensitivity; and (1) it shouldn't list theme variants whose differences are only in letter cases.

**Comment by tsujan** [comment]
Oh, my memory failed me: (2) isn't a problem because `LXQt::LXQtTheme::allThemes()` is used.

Only knowing about case-insensitivity is a logical problem.

**Comment by palinek** [comment]
I still think, the whole case insensitive comparison of theme directories is wrong concept.

**Comment by tsujan** [comment]
Superseded by https://github.com/lxqt/lxqt-config/pull/848

**Comment by tsujan** [comment]
> I still think, the whole case insensitive comparison of theme directories is wrong concept.

Yes, I know that you compare it with MS Windows file system. But it removes unnecessary complications.

**Comment by tsujan** [comment]
BTW, while doing this work, I found a self-inconsistency in `liblxqt`. It treats theme paths and theme names on the same level when making a theme object but only uses the theme names in other places.

Fortunately, it doesn't affect any code in LXQt because, everywhere, the names are used for comparisons.

**Pull request closed without merging**
