### PR TITLE
lxqt-config-brightness better UI

### PR DESCRIPTION
**Pull request by selairi**
Some changes are done in lxqt-config-brightness UI:
bajarbrillo

Related to [https://github.com/lxqt/lxqt-config/issues/404](https://github.com/lxqt/lxqt-config/issues/404)

### CODE REVIEW

**Comment by tsujan** [comment]
This GUI is nice; no confusion anymore.

Just small details — exactly as you fixed https://github.com/lxqt/lxqt-panel/pull/1385:

 1. Mouse wheel on backlight may be hard to use because the scale isn't in percents (my max brightness is 5273). This was a problem before your PR, I think.
 2. For the same reason, the buttons may not change the *visible* backlight.
 3. Please swap `☼` and `☀` with each other.

**Comment by luis-pereira** [comment]
@selairi trailing whitespaces.
It's most certainly your editor that's introducing them.

**Comment by selairi** [comment]
>     1. Mouse wheel on backlight may be hard to use because the scale isn't in percents (my max brightness is 5273). This was a problem before your PR, I think.

Done.
 
>     2. For the same reason, the buttons may not change the _visible_ backlight.

Done.

>     3. Please swap `☼` and `☀` with each other.

Done.

**Comment by selairi** [comment]
> @selairi trailing whitespaces.
> It's most certainly your editor that's introducing them.

@luis-pereira You are right. I have just enabled the option to remove trailing white spaces in my editor. Thanks.

**Comment by tsujan** [comment]
@selairi 
After compiling your last commit, I saw some issues. There may not be new -- I might haven't checked them before -- but I'm not sure.

 1. Confirmation for brightness isn't reliable here. Sometimes it works, sometimes not. For example, if I set the brightness to maximum and don't confirm the change, the slider will go back to its previous position but the brightness won't change: it will remain at its maximum value. It'll be corrected If I change it by grabbing the slider.
 2. Reset isn't reliable for brightness either. For example, after I set the brightness to maximum and confirm the change, if I press the reset button, the slider goes back to its previous position but the brightness doesn't change. Again, grabbing the slider corrects the problem. 
 3. There is no confirmation for backlight.

Sorry if my report isn't clear enough. Tell me if you need more info.

**Comment by tsujan** [comment]
@selairi 
Would you please give priority to this? I want to release lxqt-config soon but this PR is too important to be missing from the next version.

**Comment by selairi** [comment]
@tsujan Fixed!

**Comment by tsujan** [comment]
@selairi Thanks. Will test it later.

It'll go to the next version -- lxqt-config is already released.

**Comment by tsujan** [comment]
@selairi 
With the last change you made, it's fixed for my laptop screen but not for the external monitor: when I move the brightness slider (not the backlight slider) from the middle to the right and do NOT confirm the changes, the slider goes back to its previous position but the high brightness of my external monitor doesn't change.

For the laptop monitor, both brightness and backlight sliders are OK. I'm not sure what the difference is.

**Comment by selairi** [comment]
@tsujan 
> With the last change you made, it's fixed for my laptop screen but not for the external monitor: 

I have tested in my external monitor, but it works properly. I have done some changes in the brightness control. Now, it checks monitors by id.

**Comment by tsujan** [comment]
@selairi 
The problem disappeared after a reboot.

Please reverse your last commit (`if(monitor.id() == (int)output && monitor.name() == name)` had never caused a problem), squash and merge!

**Pull request merged**
