### PR TITLE
build: make touchpad settings/dependencies optional (#358)

### PR DESCRIPTION
**Pull request by Chiitoo**
Me and my options...  :]

This might not be perfect, or even completely correct in its everything, but I figured I'd ask if anything like this would be acceptable?

Thanks!

### CODE REVIEW

**Comment by yan12125** [comment]
Adding such an option is OK for me.

**Comment by palinek** [comment]
Seems OK...but isn't creating a config.h file an overkill for one define?

**Comment by Chiitoo** [comment]
> Seems OK...but isn't creating a config.h file an overkill for one define?

It's just the only method of doing it that I have seen (or remember), so it certainly could be!  :]

I'll go look around more.  Thanks!

**Comment by yan12125** [comment]
Maybe `add_definitions` can get to a similar goal?

By the way, I prefer to put `option` commands in the top level CMakeLists.txt. As a user I look at that file first for possible options.

**Comment by Chiitoo** [comment]
Changed things up, and it seems to work for me at least.

I'm not too sure about the way I sorted and grouped things up, so any opinions and/or suggestions are more than welcome.  :]

**Comment by yan12125** [comment]
Done! Thanks for the enhancement!

> It seems to be superseded by alternatives such as 'add_compile_definitions()', but that's not until CMake 3.12.something (looks like the minimum version supported right now for LXQt is 3.1.0).

I'd say requiring 3.12+ is too aggressive. Let's keep using add_definitions() until there's another problem.

**Pull request merged**
