### PR TITLE
Prerelease changes

### PR DESCRIPTION
**Pull request by tsujan**

### CODE REVIEW

**Comment by ianfarrell47** [comment]
lxqt-config-locale also got a GUI layout update

**Comment by tsujan** [comment]
It's included in CHANGELOG ("Added a separate page for GTK..."), but thanks for caring!

**Comment by ianfarrell47** [comment]
I meant lxqt-config-locale got a GUI refresh too, and bug fixes which you mention. GTK page was for lxqt-config-appearance.

**Comment by tsujan** [comment]
It's a part of https://github.com/lxqt/lxqt-config/commit/d05eebeaab9e5a40e663594345d0a907e113829c. Not every detail of every commit appears in CHANGELOG.

**Pull request merged**
