### PR TITLE
Move to new Qt5 signal/slot syntax && Fix some compilation warnings

### PR DESCRIPTION
**Pull request by adjamhub**
I also changed some indentation to be consistent and did one notable change (to let things work) set MonitorWidget::onPrimaryOutputChanged slot public

### CODE REVIEW

**Comment by tsujan** [comment]
Thanks!

I've been busy but will review and merge your PRs as soon as I find some time.

**Review by palinek — APPROVED** [review]
GTM

**Review by luis-pereira — COMMENTED** [review]
GTM.

**Comment by luis-pereira** [comment]
@adjamhub Thanks.

**Pull request merged**
