### PR TITLE
 Cleanup to Wayland message

### PR DESCRIPTION
**Pull request by isf63**
Same as https://github.com/lxqt/lxqt-globalkeys/pull/300.

### CODE REVIEW

**Comment by isf63** [comment]
The change to the main message may not be worth needing re-translation.

**Comment by stefonarch** [comment]
> The change to the main message may not be worth needing re-translation.

It will remove existing translations, I prevented it the other time but don't remember, will check.

**Comment by stefonarch** [comment]
Done here https://github.com/lxqt/lxqt-config/pull/1045 thanks!
I preferred to keep "the", or do we use "your compositor" in other places too?

**Comment by isf63** [comment]
"the" is fine. It's not worth needing new translations.

You forgot "Unsupported" being capitalized.

**Comment by stefonarch** [comment]
Oops - edited your comment instead of quoting.
Ddidn't scroll down your PR, done now.

**Pull request closed without merging**
